project:
  type: website

website:
  title: "blog"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

  sidebar:
    style:  "docked"
    search: true
    contents:
      - section: "fastai"
        contents: 

      - section: "blog"
        contents: 

     




format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



